import type { Lang } from "../i18n/translations";

/**
 * 100 palabras para jugar “Impostor”.
 * IMPORTANTE: EN y ES deben tener el MISMO largo y estar alineadas por índice.
 */

export const WORDS_EN = [
  "AIRPORT",
  "BEACH",
  "MUSEUM",
  "CINEMA",
  "HOSPITAL",
  "SCHOOL",
  "UNIVERSITY",
  "LIBRARY",
  "HOTEL",
  "RESTAURANT",
  "CAFE",
  "SUPERMARKET",
  "BANK",
  "PHARMACY",
  "POLICE STATION",
  "FIRE STATION",
  "STADIUM",
  "GYM",
  "PARK",
  "ZOO",
  "AQUARIUM",
  "THEATER",
  "CONCERT",
  "WEDDING",
  "BIRTHDAY",
  "FUNERAL",
  "JOB INTERVIEW",
  "CLASSROOM",
  "OFFICE",
  "FACTORY",
  "FARM",
  "KITCHEN",
  "BATHROOM",
  "BEDROOM",
  "LIVING ROOM",
  "ELEVATOR",
  "SUBWAY",
  "BUS",
  "TRAIN",
  "TAXI",
  "BICYCLE",
  "MOTORCYCLE",
  "CAR",
  "BOAT",
  "PLANE",
  "ROCKET",
  "PIZZA",
  "BURGER",
  "SUSHI",
  "TACO",
  "PASTA",
  "SALAD",
  "SOUP",
  "ICE CREAM",
  "CHOCOLATE",
  "COFFEE",
  "TEA",
  "WATER",
  "JUICE",
  "MILK",
  "BREAD",
  "CHEESE",
  "EGG",
  "APPLE",
  "BANANA",
  "ORANGE",
  "STRAWBERRY",
  "PINEAPPLE",
  "CARROT",
  "TOMATO",
  "POTATO",
  "ONION",
  "GARLIC",
  "DOCTOR",
  "NURSE",
  "TEACHER",
  "STUDENT",
  "CHEF",
  "WAITER",
  "POLICE OFFICER",
  "FIREFIGHTER",
  "PILOT",
  "DRIVER",
  "MECHANIC",
  "ARTIST",
  "MUSICIAN",
  "ACTOR",
  "DANCER",
  "PHOTOGRAPHER",
  "PROGRAMMER",
  "LAWYER",
  "JUDGE",
  "ATHLETE",
  "FISHERMAN",
  "GARDENER",
  "BARBER",
  "DENTIST",
  "VET",
  "SCIENTIST",
  "ENGINEER",
  "SINGER",
  "MAGICIAN",
];

export const WORDS_ES = [
  "AEROPUERTO",
  "PLAYA",
  "MUSEO",
  "CINE",
  "HOSPITAL",
  "ESCUELA",
  "UNIVERSIDAD",
  "BIBLIOTECA",
  "HOTEL",
  "RESTAURANTE",
  "CAFETERÍA",
  "SUPERMERCADO",
  "BANCO",
  "FARMACIA",
  "ESTACIÓN DE POLICÍA",
  "ESTACIÓN DE BOMBEROS",
  "ESTADIO",
  "GIMNASIO",
  "PARQUE",
  "ZOO",
  "ACUARIO",
  "TEATRO",
  "CONCIERTO",
  "BODA",
  "CUMPLEAÑOS",
  "FUNERAL",
  "ENTREVISTA DE TRABAJO",
  "AULA",
  "OFICINA",
  "FÁBRICA",
  "GRANJA",
  "COCINA",
  "BAÑO",
  "DORMITORIO",
  "SALA",
  "ASCENSOR",
  "METRO",
  "AUTOBÚS",
  "TREN",
  "TAXI",
  "BICICLETA",
  "MOTOCICLETA",
  "CARRO",
  "BARCO",
  "AVIÓN",
  "COHETE",
  "PIZZA",
  "HAMBURGUESA",
  "SUSHI",
  "TACO",
  "PASTA",
  "ENSALADA",
  "SOPA",
  "HELADO",
  "CHOCOLATE",
  "CAFÉ",
  "TÉ",
  "AGUA",
  "JUGO",
  "LECHE",
  "PAN",
  "QUESO",
  "HUEVO",
  "MANZANA",
  "PLÁTANO",
  "NARANJA",
  "FRESA",
  "PIÑA",
  "ZANAHORIA",
  "TOMATE",
  "PAPA",
  "CEBOLLA",
  "AJO",
  "DOCTOR",
  "ENFERMERA",
  "MAESTRO",
  "ESTUDIANTE",
  "CHEF",
  "MESERO",
  "POLICÍA",
  "BOMBERO",
  "PILOTO",
  "CONDUCTOR",
  "MECÁNICO",
  "ARTISTA",
  "MÚSICO",
  "ACTOR",
  "BAILARÍN",
  "FOTÓGRAFO",
  "PROGRAMADOR",
  "ABOGADO",
  "JUEZ",
  "ATLETA",
  "PESCADOR",
  "JARDINERO",
  "BARBERO",
  "DENTISTA",
  "VETERINARIO",
  "CIENTÍFICO",
  "INGENIERO",
  "CANTANTE",
  "MAGO",
];

function assertSameLength() {
  if (WORDS_EN.length !== WORDS_ES.length) {
    throw new Error(
      `WORDS_EN (${WORDS_EN.length}) and WORDS_ES (${WORDS_ES.length}) must have same length`
    );
  }
}
assertSameLength();

export function getRandomWord(lang: Lang): string {
  const list = lang === "es" ? WORDS_ES : WORDS_EN;
  return list[Math.floor(Math.random() * list.length)];
}

/**
 * Si quieres garantizar que EN/ES estén alineadas para debug:
 * devuelve el par (en, es) del mismo índice.
 */
export function getRandomWordPair(): { en: string; es: string } {
  const i = Math.floor(Math.random() * WORDS_EN.length);
  return { en: WORDS_EN[i], es: WORDS_ES[i] };
}